trigger:
- main  # Trigger build on main branch changes

pool:
  vmImage: 'windows-latest'

variables:
  BuildConfiguration: 'Development'

steps:
# 1. Check out the source code
- task: Checkout@1

# 2. Restore NuGet packages (if needed for the project)
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

# 3. Build the SSIS project
- task: MSBuild@1
  inputs:
    solution: 'SSISProject/MySSISProject.dtproj'
    msbuildArguments: '/p:Configuration=$(BuildConfiguration) /p:Platform=AnyCPU'
    configuration: '$(BuildConfiguration)'
    clean: true

# 4. Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'SSISBuildOutput'
